### ISSUE TITLE
Final Project Submission for Alysandra Zhang

### ISSUE THREAD

**Issue by Alys-217** [QMSS-G5072-2020/final_project_zhang_alysandra#1]
a0347ee16d8d74274729f6556261c1f84498063d @SUN-Wenjun @lonadai0121 @tbrambor

**Comment by lonadai0121** [comment]
2/5 below average project: only some development of functionality with limited skills performed
3/3 well commented and documented
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
2/3 Documentation of the package and its contents is largely absent.
3/3 The package installs without problems.
1/3 Testing for the package is largely absent.
